Class {
	#name : #GtClassVariableRenamedDifference,
	#superclass : #GtClassVariableDifference,
	#instVars : [
		'oldName',
		'newName'
	],
	#category : #'GToolkit-Pharo-Metamodels-Behavior - Differences'
}

{ #category : #accessing }
GtClassVariableRenamedDifference >> newName [
	^ newName
]

{ #category : #accessing }
GtClassVariableRenamedDifference >> newName: anObject [
	newName := anObject
]

{ #category : #accessing }
GtClassVariableRenamedDifference >> oldName [
	^ oldName
]

{ #category : #accessing }
GtClassVariableRenamedDifference >> oldName: anObject [
	oldName := anObject
]

{ #category : #printing }
GtClassVariableRenamedDifference >> printOn: aStream [
	aStream
		nextPutAll: 'Renamed ';
		print: self oldName;
		nextPutAll: ' class variable to ';
		print: self newName
]
