Class {
	#name : #GtPharoTestSuiteDummyTest,
	#superclass : #TestCase,
	#category : #'GToolkit-Pharo-TestSuite-Examples'
}

{ #category : #accessing }
GtPharoTestSuiteDummyTest >> testOne [
	^ 1
]

{ #category : #accessing }
GtPharoTestSuiteDummyTest >> testSeven [
	^ 7
]

{ #category : #accessing }
GtPharoTestSuiteDummyTest >> testThree [
	^ 3
]

{ #category : #accessing }
GtPharoTestSuiteDummyTest >> testTwo [
	^ 2
]
