Class {
	#name : #GtRefactoringsViewModelExecutedRefactoringsComputed,
	#superclass : #GtRefactoringsViewModelExecutedRefactoringsStateAnnouncement,
	#instVars : [
		'source'
	],
	#category : #'GToolkit-Pharo-Coder-UI-Refactorings New'
}

{ #category : #accessing }
GtRefactoringsViewModelExecutedRefactoringsComputed >> source [
	^ source
]

{ #category : #accessing }
GtRefactoringsViewModelExecutedRefactoringsComputed >> source: anObject [
	source := anObject
]
