Class {
	#name : #Gt2PharoBehaviorCoderNavigationViewModelViewModelDeselected,
	#superclass : #Announcement,
	#instVars : [
		'pharoBehaviorCoderNavigationViewModel'
	],
	#category : #'GToolkit-Pharo-Coder2-Navigation - Events'
}

{ #category : #generated }
Gt2PharoBehaviorCoderNavigationViewModelViewModelDeselected >> pharoBehaviorCoderNavigationViewModel [
	<objectGetter: #behavior>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectGetterTemplate'>

	^ pharoBehaviorCoderNavigationViewModel
]

{ #category : #generated }
Gt2PharoBehaviorCoderNavigationViewModelViewModelDeselected >> pharoBehaviorCoderNavigationViewModel: aPharoBehaviorCoderNavigationViewModel [
	<objectSetter: #behavior>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectSetterTemplate'>

	pharoBehaviorCoderNavigationViewModel := aPharoBehaviorCoderNavigationViewModel
]
