Class {
	#name : #Gt2PharoTagCoderRemovedAnnouncement,
	#superclass : #Announcement,
	#instVars : [
		'pharoTagCoder'
	],
	#category : #'GToolkit-Pharo-Coder2-Events'
}

{ #category : #generated }
Gt2PharoTagCoderRemovedAnnouncement >> pharoTagCoder [
	<objectGetter: #tag>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectGetterTemplate'>

	^ pharoTagCoder
]

{ #category : #generated }
Gt2PharoTagCoderRemovedAnnouncement >> pharoTagCoder: aPharoTagCoder [
	<objectSetter: #tag>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectSetterTemplate'>

	pharoTagCoder := aPharoTagCoder
]
