Class {
	#name : #Gt2PharoTagCoderNavigationViewModelAddedAnnouncement,
	#superclass : #Announcement,
	#instVars : [
		'pharoTagCoderNavigationViewModel'
	],
	#category : #'GToolkit-Pharo-Coder2-Navigation - Events'
}

{ #category : #generated }
Gt2PharoTagCoderNavigationViewModelAddedAnnouncement >> pharoTagCoderNavigationViewModel [
	<objectGetter: #tag>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectGetterTemplate'>

	^ pharoTagCoderNavigationViewModel
]

{ #category : #generated }
Gt2PharoTagCoderNavigationViewModelAddedAnnouncement >> pharoTagCoderNavigationViewModel: aPharoTagCoderNavigationViewModel [
	<objectSetter: #tag>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectSetterTemplate'>

	pharoTagCoderNavigationViewModel := aPharoTagCoderNavigationViewModel
]
