Class {
	#name : #Gt2PharoPackageCoderViewModelViewModelSelected,
	#superclass : #Announcement,
	#instVars : [
		'pharoPackageCoderViewModel'
	],
	#category : #'GToolkit-Pharo-Coder2-Events'
}

{ #category : #generated }
Gt2PharoPackageCoderViewModelViewModelSelected >> pharoPackageCoderViewModel [
	<objectGetter: #package>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectGetterTemplate'>

	^ pharoPackageCoderViewModel
]

{ #category : #generated }
Gt2PharoPackageCoderViewModelViewModelSelected >> pharoPackageCoderViewModel: aPharoPackageCoderViewModel [
	<objectSetter: #package>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectSetterTemplate'>

	pharoPackageCoderViewModel := aPharoPackageCoderViewModel
]
