Class {
	#name : #Gt2PharoPackageCoderNavigationViewModelRemovedAnnouncement,
	#superclass : #Announcement,
	#instVars : [
		'pharoPackageCoderNavigationViewModel'
	],
	#category : #'GToolkit-Pharo-Coder2-Navigation - Events'
}

{ #category : #generated }
Gt2PharoPackageCoderNavigationViewModelRemovedAnnouncement >> pharoPackageCoderNavigationViewModel [
	<objectGetter: #package>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectGetterTemplate'>

	^ pharoPackageCoderNavigationViewModel
]

{ #category : #generated }
Gt2PharoPackageCoderNavigationViewModelRemovedAnnouncement >> pharoPackageCoderNavigationViewModel: aPharoPackageCoderNavigationViewModel [
	<objectSetter: #package>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectSetterTemplate'>

	pharoPackageCoderNavigationViewModel := aPharoPackageCoderNavigationViewModel
]
