Class {
	#name : #Gt2PharoSelectedBehaviorCoderNavigationViewModelChanged,
	#superclass : #Announcement,
	#instVars : [
		'selectedBehaviorCoderNavigationViewModel'
	],
	#category : #'GToolkit-Pharo-Coder2-Navigation - Events'
}

{ #category : #generated }
Gt2PharoSelectedBehaviorCoderNavigationViewModelChanged >> selectedBehaviorCoderNavigationViewModel [
	<objectGetter: #behavior>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectGetterTemplate'>

	^ selectedBehaviorCoderNavigationViewModel
]

{ #category : #generated }
Gt2PharoSelectedBehaviorCoderNavigationViewModelChanged >> selectedBehaviorCoderNavigationViewModel: aSelectedBehaviorCoderNavigationViewModel [
	<objectSetter: #behavior>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectSetterTemplate'>

	selectedBehaviorCoderNavigationViewModel := aSelectedBehaviorCoderNavigationViewModel
]
