Class {
	#name : #Gt2PharoPackageActionCoderViewModelExpandedChanged,
	#superclass : #Announcement,
	#instVars : [
		'expanded'
	],
	#category : #'GToolkit-Pharo-Coder2-Package Coder - Events'
}

{ #category : #generated }
Gt2PharoPackageActionCoderViewModelExpandedChanged >> expanded [
	<objectGetter: #packageAction>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectGetterTemplate'>

	^ expanded
]

{ #category : #generated }
Gt2PharoPackageActionCoderViewModelExpandedChanged >> expanded: aExpanded [
	<objectSetter: #packageAction>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectSetterTemplate'>

	expanded := aExpanded
]
