Class {
	#name : #Gt2PharoBehaviorCoderRemovedAnnouncement,
	#superclass : #Announcement,
	#instVars : [
		'pharoBehaviorCoder'
	],
	#category : #'GToolkit-Pharo-Coder2-Events'
}

{ #category : #generated }
Gt2PharoBehaviorCoderRemovedAnnouncement >> pharoBehaviorCoder [
	<objectGetter: #behavior>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectGetterTemplate'>

	^ pharoBehaviorCoder
]

{ #category : #generated }
Gt2PharoBehaviorCoderRemovedAnnouncement >> pharoBehaviorCoder: aPharoBehaviorCoder [
	<objectSetter: #behavior>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectSetterTemplate'>

	pharoBehaviorCoder := aPharoBehaviorCoder
]
