Class {
	#name : #Gt2PharoMethodCoderAddedAnnouncement,
	#superclass : #Announcement,
	#instVars : [
		'pharoMethodCoder'
	],
	#category : #'GToolkit-Pharo-Coder2-Events'
}

{ #category : #generated }
Gt2PharoMethodCoderAddedAnnouncement >> pharoMethodCoder [
	<objectGetter: #method>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectGetterTemplate'>

	^ pharoMethodCoder
]

{ #category : #generated }
Gt2PharoMethodCoderAddedAnnouncement >> pharoMethodCoder: aPharoMethodCoder [
	<objectSetter: #method>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectSetterTemplate'>

	pharoMethodCoder := aPharoMethodCoder
]
