Class {
	#name : #Gt2PharoSelectedTagCoderNavigationViewModelChanged,
	#superclass : #Announcement,
	#instVars : [
		'selectedTagCoderNavigationViewModel'
	],
	#category : #'GToolkit-Pharo-Coder2-Navigation - Events'
}

{ #category : #generated }
Gt2PharoSelectedTagCoderNavigationViewModelChanged >> selectedTagCoderNavigationViewModel [
	<objectGetter: #tag>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectGetterTemplate'>

	^ selectedTagCoderNavigationViewModel
]

{ #category : #generated }
Gt2PharoSelectedTagCoderNavigationViewModelChanged >> selectedTagCoderNavigationViewModel: aSelectedTagCoderNavigationViewModel [
	<objectSetter: #tag>
	<generatedFrom: #'GtRobocoderMetamodelAnnouncementTemplate>>#objectSetterTemplate'>

	selectedTagCoderNavigationViewModel := aSelectedTagCoderNavigationViewModel
]
