"
I am a {{gtClass:GtFiltersDummyObjectWithExampleStates}}.
I am used for testing purposes, see my {{gtClass:GtFiltersDummyObjectWithFailureExampleStates|label=references|show=#gtAllReferencesFor:|expanded=true}}:

"
Class {
	#name : #GtFiltersDummyObjectWithFailureExampleStates,
	#superclass : #GtFiltersDummyObjectWithExampleStates,
	#category : #'GToolkit-Pharo-Coder-Examples-Filters - UI'
}

{ #category : #examples }
GtFiltersDummyObjectWithFailureExampleStates >> three [
	<gtExample>
	<noTest>
	self assert: false
]
