"
I am a {{gtClass:GtFiltersDummyObjectWithExampleStates}}.
I am used for testing purposes, see my {{gtClass:GtFiltersDummyObjectWithSuccessExampleStates|label=references|show=#gtAllReferencesFor:|expanded=true}}:

"
Class {
	#name : #GtFiltersDummyObjectWithSuccessExampleStates,
	#superclass : #GtFiltersDummyObjectWithExampleStates,
	#category : #'GToolkit-Pharo-Coder-Examples-Filters - UI'
}

{ #category : #examples }
GtFiltersDummyObjectWithSuccessExampleStates >> one [
	<gtExample>
	^ 42
]
