Class {
	#name : #GtPharoDummySixObject,
	#superclass : #Object,
	#category : #'GToolkit-Pharo-Coder-Examples-Dummies'
}

{ #category : #accessing }
GtPharoDummySixObject >> classifiedMethod [
]

{ #category : #'as yet unclassified' }
GtPharoDummySixObject >> unclassifiedMethodOne [
	"Leave this method unclassified"
]

{ #category : #'as yet unclassified' }
GtPharoDummySixObject >> unclassifiedMethodTwo [
	"Leave this method unclassified"
]
