Class {
	#name : #GtPharoRenameSelectorModelAnnouncement,
	#superclass : #Announcement,
	#instVars : [
		'selectorModel'
	],
	#category : #'GToolkit-Pharo-Coder-AddOns-Refactoring - Method New'
}

{ #category : #accessing }
GtPharoRenameSelectorModelAnnouncement >> selectorModel [
	^ selectorModel
]

{ #category : #accessing }
GtPharoRenameSelectorModelAnnouncement >> selectorModel: anObject [
	selectorModel := anObject
]
