Class {
	#name : #GtPharoRenameSelectorElementSignal,
	#superclass : #AnObsoleteGtPharoRenameSelectorSignal,
	#instVars : [
		'element'
	],
	#category : #'GToolkit-Pharo-Coder-AddOns-Refactoring - Method New'
}

{ #category : #accessing }
GtPharoRenameSelectorElementSignal >> element [
	^ element
]

{ #category : #accessing }
GtPharoRenameSelectorElementSignal >> element: anObject [
	element := anObject
]
