Class {
	#name : #GtPharoStreamingMethodsFiltersElementStencilDefaultChangedSignal,
	#superclass : #GtFilterSignal,
	#instVars : [
		'previousClass',
		'newClass'
	],
	#category : #'GToolkit-Pharo-Coder-Method-UI-Support'
}

{ #category : #accessing }
GtPharoStreamingMethodsFiltersElementStencilDefaultChangedSignal >> newClass [
	^ newClass
]

{ #category : #accessing }
GtPharoStreamingMethodsFiltersElementStencilDefaultChangedSignal >> newClass: anObject [
	newClass := anObject
]

{ #category : #accessing }
GtPharoStreamingMethodsFiltersElementStencilDefaultChangedSignal >> previousClass [
	^ previousClass
]

{ #category : #accessing }
GtPharoStreamingMethodsFiltersElementStencilDefaultChangedSignal >> previousClass: anObject [
	previousClass := anObject
]
